name: mmalign
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Python 版本
  - python=3.10
  - pip>=23.0
  
  # 核心科学计算库
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - scikit-learn>=1.3
  - matplotlib>=3.8
  - plotly>=5.22
  
  # PyTorch (自动适配 Apple Silicon)
  - pytorch::pytorch>=2.0
  - pytorch::torchvision>=0.15
  - pytorch::torchaudio>=2.0
  
  # 音视频处理
  - librosa>=0.10
  - ffmpeg
  
  # Jupyter 环境
  - jupyter>=1.0
  - notebook>=7.0
  - ipykernel>=6.25
  - ipywidgets>=8.1
  
  # 可视化增强
  - seaborn>=0.13
  
  # 通过 pip 安装的包（避免 conda 依赖问题）
  - pip:
      # 音频处理
      - soundfile>=0.12.1
      - SoundFile>=0.12.1
      
      # 视频处理
      - opencv-python-headless>=4.9.0
      
      # Web 应用
      - streamlit>=1.36.0
      
      # NLP 和 Transformers
      - transformers>=4.30.0
      - tokenizers>=0.13.0
      - sentencepiece>=0.1.99
      
      # 时序对齐
      - fastdtw>=0.3.4
      - dtaidistance>=2.3.10
      
      # 工具库
      - python-dateutil>=2.9
      - tqdm>=4.66
      
      # 数据处理增强
      - openpyxl>=3.1
      - h5py>=3.9
      - psycopg2-binary>=2.9.9
